#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H

#define CAUSE_NONE 0x0
#define CAUSE_LENGTH_VIOLATION 0x1
#define CAUSE_TAG_VIOLATION 0x2
#define CAUSE_SEAL_VIOLATION 0x3
#define CAUSE_TYPE_VIOLATION 0x4
#define CAUSE_CALL_TRAP 0x5
#define CAUSE_RETURN_TRAP 0x6
#define CAUSE_TRUSTED_SYSTEM_STACK_OVERFLOW 0x7
#define CAUSE_SOFTWARE_DEFINED_PERMISSION_VIOLATION 0x8
#define CAUSE_MMU_PROHIBITS_STORE_CAPABILITY 0x9
#define CAUSE_BOUNDS_CANNOT_BE_REPRESENTED_EXACTLY 0xa
#define CAUSE_GLOBAL_VIOLATION 0x10
#define CAUSE_PERMIT_EXECUTE_VIOLATION 0x11
#define CAUSE_PERMIT_LOAD_VIOLATION 0x12
#define CAUSE_PERMIT_STORE_VIOLATION 0x13
#define CAUSE_PERMIT_LOAD_CAPABILITY_VIOLATION 0x14
#define CAUSE_PERMIT_STORE_CAPABILITY_VIOLATION 0x15
#define CAUSE_PERMIT_STORE_LOCAL_CAPABILITY_VIOLATION 0x16
#define CAUSE_PERMIT_SEAL_VIOLATION 0x17
#define CAUSE_ACCESS_SYSTEM_REGISTERS_VIOLATION 0x18
#define CAUSE_PERMIT_CCALL_VIOLATION 0x19
#define CAUSE_ACCESS_CCALL_IDC_VIOLATION 0x1a
#define CAUSE_PERMIT_UNSEAL_VIOLATION 0x1b
#define CAUSE_PERMIT_SET_CID_VIOLATION 0x1c

#define CAP_IDX_PCC 0x20
#define CAP_IDX_DDC 0x21

#endif
